Repository nginx/nginx-plus-go-client, pull requests merged in 2021-06, with the labels that each got.

#71 Update workflows
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
Labels: chore

#70 Update Dockerfile, NGINX and golangci-lint versions
  Makefile
  docker/Dockerfile
Labels: chore, dependencies

#72 Update path for NGINX cert and key
  .github/workflows/ci.yml
  Makefile
  docker/Dockerfile
Labels: chore

#73 Add golangci-lint config
  .github/workflows/lint.yml
  .golangci.yml
  Makefile
  client/nginx.go
  client/nginx_test.go
  tests/client_no_stream_test.go
  tests/client_test.go
Labels: chore

#74 chore: build client and test on scheduled runs
  .github/workflows/ci.yml
Labels: chore

#75 Restore closing the HTTP response
  client/nginx.go
Labels: bug
