Repository nginx/nginx-plus-go-client, pull requests merged in 2022-10, with the labels that each got.

#119 Remove dependency on a deprecated package
  client/nginx.go
Labels: chore

#116 Update Slack announce channel
  .goreleaser.yaml
Labels: chore

#122 Bump Go to 1.19
  Makefile
  go.mod
Labels: dependencies

#123 Remove unneeded Plus version
  .github/workflows/ci.yml
  docker/Dockerfile
Labels: chore

#120 Create SECURITY.md
  SECURITY.md
Labels: documentation

#125 Update GitHub Actions runners to Ubuntu 22.04
  .github/workflows/ci.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/fossa.yml
  .github/workflows/lint.yml
  .github/workflows/notifications.yml
  .github/workflows/release-drafter.yml
  .github/workflows/stale.yml
Labels: chore
