Repository nginx/nginx-plus-go-client, pull requests merged in 2023-10, with the labels that each got.

#174 Add checks to see if stream endpoints exist before calling them
  client/nginx.go
  client/nginx_test.go
  go.mod
  go.sum
Labels: dependencies

#176 Bump Go to 1.21
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  client/nginx.go
  go.mod
  go.sum
Labels: dependencies, chore

#179 Add setup go step
  .github/workflows/ci.yml
Labels: chore
