Repository nginx/nginx-plus-go-client, pull requests merged in 2023-08, with the labels that each got.

#141 Add OpenSSF Scorecard
  .github/workflows/scorecard.yml
  README.md
Labels: documentation, chore

#142 Add pre-commit and fix issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
  .markdownlint-cli2.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ISSUE_LIFECYCLE.md
  README.md
  SECURITY.md
Labels: documentation, chore

#148 Bump NGINX Plus to R30
  Makefile
Labels: dependencies

#151 Bump Debian to 12
  docker/Dockerfile
Labels: dependencies

#152 Use Docker Compose for tests
  .github/workflows/ci.yml
  Makefile
  compose.yaml
  docker/Dockerfile
  docker/nginx.conf
  docker/nginx_no_stream.conf
Labels: chore

#154 Fix api support range in readme
  README.md
Labels: documentation

#156 Skip running OpenSSF check on forks
  .github/workflows/scorecard.yml
Labels: bug

#158 Release 0.11.0
  CHANGELOG.md
Labels: documentation
