Repository nginx/nginx-plus-go-client, pull requests merged in 2024-09, with the labels that each got.

#360 Call NGINX Plus API in a series of parallel requests
  client/nginx.go
  client/nginx_test.go
  go.mod
  go.sum
Labels: dependencies

#378 Skip dependency review run on merge queue
  .github/workflows/dependency-review.yml
  .github/workflows/lint.yml
Labels: chore

#379 Skip workflow runs the right way
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependency-review.yml
Labels: chore

#366 Update OpenSSF badge
  README.md
Labels: documentation

#364 Use CLA GitHub Action
  .github/workflows/f5-cla.yml
  .yamllint.yaml
  CONTRIBUTING.md
Labels: documentation, chore

#367 Add permissions for GoReleaser
  .github/workflows/ci.yml
Labels: chore

#383 Support cancellation of NGINX Plus API calls
  .golangci.yml
  client/nginx.go
  client/nginx_test.go
  tests/client_no_stream_test.go
  tests/client_test.go
Labels: change, tests

#380 Add WithMaxAPIVersion Option to NginxClient
  .gitignore
  client/nginx.go
  client/nginx_test.go
Labels: community

#382 Add more linters
  .golangci.yml
  Makefile
  client/nginx_test.go
  tests/client_no_stream_test.go
  tests/client_test.go
Labels: chore, tests

#386 Update go module to use v2
  go.mod
  tests/client_no_stream_test.go
  tests/client_test.go
Labels: dependencies, chore, tests
