Repository nginx/nginx-plus-go-client, pull requests merged in 2024-07, with the labels that each got.

#307 Use yamllint action from reviewdog
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/dependency-review.yml
  .github/workflows/fossa.yml
  .github/workflows/lint.yml
  .github/workflows/scorecard.yml
Labels: chore

#308 Update CodeQL workflow
  .github/workflows/codeql-analysis.yml
Labels: chore

#309 Add yamllint to pre-commit config
  .pre-commit-config.yaml
Labels: chore

#310 Add linters that check for bugs
  .golangci.yml
  client/nginx.go
  client/nginx_test.go
Labels: chore

#311 Update keepalive field for http upstreams
  client/nginx.go
Labels: bug

#318 Automatically close milestones
  .github/workflows/ci.yml
  .goreleaser.yaml
Labels: chore

#326 Add doctoc to automatically generate TOCs
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  release-process.md
Labels: documentation, chore
